name: Homer
version: "1.21"
slug: homer
description: A very simple static homepage for your server
url: https://github.com/Eskander/ha-addon-homer
image: ghcr.io/eskander/ha-addon-homer
codenotary: mail@eskander.tn
arch:
  - amd64
  - aarch64
init: false
ingress: true
ingress_port: 8080
panel_icon: mdi:server
ports:
  8080/tcp: null
map:
  - type: addon_config
    path: /www/assets
    read_only: false
