name: Homer
version: "1.0"
slug: homer
description: A dead simple static HOMe for your servER to keep your services on hand from a simple yaml config. 
url: "https://github.com/Eskander/ha-addon-homer/tree/main/homer"
image: "ghcr.io/eskander/ha-addon-homer-{arch}"
arch:
  - armv7
  - aarch64
  - amd64
init: false
ports:
  8080/tcp: 8080
map:
  - addon_config:rw
