name: Dependabot Auto-Merge

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: Dependabot Auto-Merge
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && !contains(github.event.pull_request.title, vars.BASE_PACKAGE)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Enable auto-merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit "${{ github.event.pull_request.number }}" --add-label "auto-merged"
          gh pr merge --auto --merge "${{ github.event.pull_request.number }}"
