name: Dependabot Auto-Merge

on:
  pull_request_target:
    branches:
      - main
    paths-ignore:
      - 'src/Dockerfile'

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: Dependabot Auto-Merge
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Approve PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review --approve ${{github.event.pull_request.html_url}}

      - name: Enable auto-merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit --add-label "auto-merged" "${{ github.event.pull_request.html_url }}"
          gh pr merge --auto --merge "${{ github.event.pull_request.html_url }}"
