name: Build Add-on

on:
  push:
    branches:
      - release
    paths:
      - 'src/config.yaml'
      - 'src/Dockerfile'
      - 'src/rootfs/**'
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - release
    paths:
      - 'src/config.yaml'
      - 'src/Dockerfile'
      - 'src/rootfs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deploy'))
    name: Build multi-arch add-on
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./src"

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare tags
        id: tags
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository }}"
          VERSION="${{ steps.info.outputs.version }}"
          
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            TAGS="${IMAGE_NAME}:pr-${{ github.event.pull_request.number }}"
          else
            TAGS="${IMAGE_NAME}:${VERSION},${IMAGE_NAME}:latest"
          fi
          
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./src
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.tags.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.created=${{ github.event.repository.pushed_at }}
            org.opencontainers.image.version=${{ steps.info.outputs.version }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=Apache-2.0
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.documentation=https://github.com/${{ github.repository }}/blob/main/README.md
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.authors=${{ github.repository_owner }}
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
