name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - release

jobs:
  lint:
    name: Lint Add-on
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4.2.2

      - name: Run Home Assistant Add-on Lint
        uses: frenck/action-addon-linter@v2.18.0
        with:
          path: "./src"
